<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="1" name="One passing scenario, one failing scenario" tests="2" time="0.000865">
<testcase classname="One passing scenario, one failing scenario.Passing" name="Passing" time="0.000360">
</testcase>
<testcase classname="One passing scenario, one failing scenario.Failing" name="Failing" time="0.000505">
  <failure message="failed Failing" type="failed">
Scenario: Failing

Given a failing scenario

Message:
 (RuntimeError)
./features/step_definitions/steps.rb:6:in `/a failing scenario/'
features/one_passing_one_failing.feature:7:in `Given a failing scenario'  </failure>
</testcase>
</testsuite>
